weather/urls.py
from django.urls import path
from . import views


app_name = 'weather'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/delete', views.delete_city, name='delete-city'),
    path('<int:pk>', views.forecast, name='forecast'),
    path('<int:pk>/test', views.test, name='test')
]

weather_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls'))
]

weather/models.py
from django.db import models
from django_countries.fields import CountryField


class City(models.Model):
    name = models.CharField(max_length=20, blank=True)
    temperature = models.FloatField(null=True, blank=True)
    description = models.CharField(max_length=20, blank=True)
    icon = models.FileField(blank=True)
    country = CountryField(blank=True, blank_label='select country (optional)')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'cities'


class BucketManager(models.Manager):
    def new_or_get(self, request):
        bucket_id = request.session.get("bucket_id", None)
        request.session.save()
        qs = self.get_queryset().filter(id=bucket_id)
        if qs.count() == 1:
            new_obj = False
            bucket_obj = qs.first()
            bucket_obj.save()
        else:
            bucket_obj = Bucket.objects.new()
            new_obj = True
            request.session['bucket_id'] = bucket_obj.id
        return bucket_obj, new_obj

    def new(self):
        return self.model.objects.create()


class Bucket(models.Model):
    cities = models.ManyToManyField(City, blank=True)

    objects = BucketManager()

    def __str__(self):
        return str(self.id)

weather/forms.py
from django.forms import ModelForm, TextInput, ValidationError
from .models import City
import requests
import os

weather_url = os.environ.get("WEATHER_URL")
forecast_url = os.environ.get("FORECAST_URL")


class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name', 'country']
        widgets = {'name': TextInput(attrs={'class': 'input', 'placeholder': 'City Name'})}

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        country = cleaned_data.get('country')
        print("Cleaned name: " + str(name))
        print("Cleaned country: " + str(country))
        if country == '':
            url = weather_url.format(name, '', '')
            print(url)
            r = requests.get(url).json()
        else:
            url = weather_url.format(name, ',', country)
            print(url)
            r = requests.get(url).json()
        print(r)
        if r['cod'] == "404":
            print('City not found ValidationError')
            raise ValidationError('City not found. Please check if spelling or country selected is correct.')
        if r['cod'] == "400":
            print('No city entered ValidationError')
            raise ValidationError('Please enter a city name.')

weather/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Bucket, City
from .forms import CityForm
import requests
from collections import defaultdict
import os
from .datetime_functions import get_timezone, get_weekday, get_datetime, get_time


weather_url = os.environ.get("WEATHER_URL")
forecast_url = os.environ.get("FORECAST_URL")


def index(request):
    bucket_obj, new_obj = Bucket.objects.new_or_get(request)

    form = CityForm()

    if request.method == 'POST':
        form = CityForm(request.POST)
        if form.is_valid():
            city_obj = form.save()
            form = CityForm
            print('Form: ' + str(city_obj) + ', Type: ' + str(type(city_obj)))
            print('Bucket: ' + str(bucket_obj))
            bucket_obj.cities.add(city_obj)

    print(bucket_obj, new_obj)

    my_cities = bucket_obj.cities.all()

    print(my_cities)

    print(type(bucket_obj))

    for city in my_cities:
        city.name = city.name.title()
        if city.country == None:
            r = requests.get(weather_url.format(city.name, '', city.country)).json()
        else:
            r = requests.get(weather_url.format(city.name, ',', city.country)).json()
        city.temperature = round(r['main']['temp'])
        city.description = r['weather'][0]['description'].capitalize()
        city.icon = r['weather'][0]['icon']
        city.country = r['sys']['country']

    context = {'cities': my_cities, 'form': form}
    return render(request, 'weather/weather.html', context)


def delete_city(request, pk):
    city = City.objects.get(pk=pk)
    city.delete()
    return redirect('weather:index')


def forecast(request, pk):
    city = City.objects.get(pk=pk)
    city.name = city.name.title()

    if city.country == None:
        r = requests.get(forecast_url.format(city.name, '', city.country)).json()
    else:
        r = requests.get(forecast_url.format(city.name, ',', city.country)).json()

    if city.country == None:
        rn = requests.get(weather_url.format(city.name, '', city.country)).json()
    else:
        rn = requests.get(weather_url.format(city.name, ',', city.country)).json()

    forecasts = range(r['cnt'])

    forecast_dict = defaultdict(list)

    longitude = r['city']['coord']['lon']
    latitude = r['city']['coord']['lat']

    weather_now = {
        'temperature' : round(rn['main']['temp']),
        'description' : rn['weather'][0]['description'].capitalize(),
        'icon' : rn['weather'][0]['icon'],
        'day' : 'Today',
        'time' : 'Now'
    }

    forecast_dict['Today'].append(weather_now)

    for f in forecasts:
        weather_forecast = {
        'temperature' : round(r['list'][f]['main']['temp']),
        'description' : r['list'][f]['weather'][0]['description'].capitalize(),
        'icon' : r['list'][f]['weather'][0]['icon'],
        'day' : get_weekday(get_timezone(get_datetime(r['list'][f]['dt']), longitude, latitude)),
        'time' : get_time(get_timezone(get_datetime(r['list'][f]['dt']), longitude, latitude))
        }
        forecast_dict[weather_forecast['day']].append(weather_forecast)

    forecast_data = dict(forecast_dict)

    context = {'city': city, 'forecast_data': forecast_data}

    return render(request, 'weather/forecast.html', context)


def test(request, pk):
    city = City.objects.get(pk=pk)
    test_url = forecast_url.format(city.name, ',', city.country)

    if city.country == None:
        r = requests.get(forecast_url.format(city.name, '', city.country)).json()
    else:
        r = requests.get(forecast_url.format(city.name, ',', city.country)).json()

    my_datetime = get_datetime(r['list'][0]['dt'])

    my_date = my_datetime.date()

    today = datetime.date.today()

    context = {'city': city, 'test_url': test_url, 'my_datetime': my_datetime, 'my_date': my_date, 'today': today}

    return render(request, 'weather/test.html', context)

weather/templates/weather/forecast.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Weather</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
    {% load staticfiles %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'weather/style.css' %}"/>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script>
    $( function() {
        $( "#tabs" ).tabs();
    } );
    </script>
</head>

<body>
    <section class="hero is-primary">
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{% url 'weather:index' %}" class="navbar-item">
                                <span class="icon">
                                    <i class="fas fa-arrow-left"></i>
                                </span>
                                Back
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    {{ city.name }} 5 Day Forecast
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div id="tabs">
                <ul>
                    {% for day, day_list in forecast_data.items %}
                        <li> <a href="#{{ day }}"> <span class="title"> {{ day }} </span> </a> </li>
                    {% endfor %}
                </ul>
                {% for day, day_list in forecast_data.items %}
                    <div id="{{ day }}">
                        <div class="scrolls">
                            <div class="columns is-gapless">
                                {% for weather_forecast in day_list %}
                                    <div class="column is-narrow">
                                        <div class="box" style="width: 300px;">
                                            <article class="media">
                                                <div class="media-content">
                                                    <div class="content">
                                                        <img src="http://openweathermap.org/img/w/{{ weather_forecast.icon }}.png" alt="Image" width="50" height="50">
                                                        <p>
                                                            <span class="title">{{ weather_forecast.time }}</span>
                                                            <br>
                                                            <span class="subtitle">{{ weather_forecast.temperature }} °C</span>
                                                            <br>
                                                            <span class="subtitle">{{ weather_forecast.description }}</span>
                                                        </p>
                                                    </div>
                                                </div>
                                            </article>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
</body>

weather/templates/weather/test.html
{{ city.name }}
<br>
{{ test_url }}
<br>
{{ my_datetime }}
<br>
{{ my_date }}
<br>
{{ today }}

weather/templates/weather/weather.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Weather</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'weather/style.css' %}"/>
</head>

<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    What's the weather like?
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="field has-addons">
                            <div class="control is-expanded">
                                {{ form.name }}
                                {% if form.errors %}
                                        <strong class="help is-danger">{{ form.non_field_errors }}</strong>
                                {% endif %}
                            </div>
                            <div class="control">
                                <button type="submit" class="button is-info">
                                    Add City
                                </button>
                            </div>
                        </div>
                        <div class="field has-addons">
                            <div class="control is-expanded">
                                {{ form.country }}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns is-multiline">
                {% for city in cities %}
                    <div class="column is-3">
                        <div class="box">
                            <article class="media">
                                <div class="media-left">
                                    <figure class="image is-50x50">
                                        <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
                                    </figure>
                                </div>
                                <div class="media-content">
                                    <div class="content">
                                        <form action="{% url 'weather:delete-city' city.id %}", method="post", style="float: right;">
                                            {% csrf_token %}
                                            <input type="hidden" name="city_id" value="{{ city.id }}" />
                                            <button type="submit" class="delete">
                                            </button>
                                        </form>
                                        <span class="title">{{ city.name }}</span>
                                        <br>
                                        {{ city.country.name }}
                                        <br>
                                        <span class="subtitle">{{ city.temperature }} °C</span>
                                        <br>
                                        {{ city.description }}
                                        <br>
                                        <a href="{% url 'weather:forecast' city.id %}" class="button is-link">Five Day Forecast</a>
                                    </div>
                                </div>
                            </article>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

</body>

</html>